version: "3.8"

services:
  stt:
    build: ./stt
    ports:
      - "8001:8001"

  tts:
    build: ./tts
    ports:
      - "8002:8002"

  cv-parser:
    build: ./cv-parser
    ports:
      - "8003:8003"

  question-gen:
    build: ./question-gen
    ports:
      - "8004:8004"
